version: "3.9"

services:
  stream:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipeless start --stages-dir .
    ports:
      - "8012:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PIPELESS_INPUT_ADDRESS_HOST=worker
      - PIPELESS_INPUT_ADDRESS_PORT=3030
      - PIPELESS_OUTPUT_ADDRESS_HOST=stream
      - PIPELESS_OUTPUT_ADDRESS_PORT=3031
    volumes:
      - './input/:/input/'
      - './output/:/output/'
    runtime: nvidia
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"