version: "3"

services:
  stream:
    image: miguelaeh/pipeless:latest-tensorrt
    command: pipeless add stream --input-uri "file:///home/sedan/Projects/video-demo-cafe/demo-video-cafe.mp4" --output-uri "file:///app/output.mp4" --frame-path "onnx-yolo"
    volumes:
      - 'onnx-yolo/:/app/onnx-yolo/'
      - 'demo-video-cafe.mp4/:/app/demo-video-cafe.mp4'
    runtime: nvidia
    devices:
      - /dev/snd:/dev/snd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true

  worker:
    image: miguelaeh/pipeless:latest-tensorrt
    command: pipeless start --stages-dir .
    volumes:
      - 'onnx-yolo/:/app/onnx-yolo/'
    runtime: nvidia
    devices:
      - /dev/snd:/dev/snd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    stdin_open: true
    tty: true