# Use the official PostgreSQL image from the Docker Hub
FROM postgres:14-alpine

# Set the working directory inside the container
#WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL script into the container
#COPY ./init_db.sql ./init_db.sql

# Expose the default PostgreSQL port
EXPOSE 5432